# Setup
path:         https://ipfs.io/ipfs/QmVhFMu7ryuFyRXm8gpxWmVuSsLR5H9Z91j8YcTrc9GmUL
baseurl:      https://ipfs.io/ipfs/QmVhFMu7ryuFyRXm8gpxWmVuSsLR5H9Z91j8YcTrc9GmUL
markdown:     kramdown
google_analytics:
github:       multiformats/website

# Metadata
title:        multiformats
description:  A collection of protocols for future-proofing systems, today.
license:      MIT

# Logo
# The type is from OGP. See http://ogp.me
#logo:
#  name:       caiman.png
#  type:       image/png
#  width:      800
#  height:     800

# About/contact
author:
  name:       Protocol Labs Inc.
  url:        http://ipfs.io

# Open Source Protocol
# See http://osprotocol.com
os:
  repo:     https://github.com/multiformats/website
  src:      git@github.com:multiformats/website.git
  issues:   https://github.com/multiformats/website/issues
  branch:   gh-pages
  rcs_type: git

# Maintainer (normally on GitHub)
maintainer:
  name: The Multiformats Organization
  link: https://github.com/multiformats

# Gems
